### ISSUE TITLE
Fix chromium version at kiosk-playbook

### ISSUE THREAD

**Issue by RafaRuiz** [Sentry-Interactive/kiosk-playbook#25]
We've got failures on different Kiosks and I've been narrowing down the issue, which is `snap` installing higher versions of `chromium` as long as they get into the `stable` channel.

We need to fix one of the working versions to `chromium` to install the same one.

For example `119.0.6045.10` is working

**Comment by mpbarnwell** [comment]
Best I can do is #26 since snap nor the ansible playbooks for snap seem to let you control the version, only the release channel.

**Comment by mpbarnwell** [comment]
Stable is now version 119, we need to revert back to stable instead of beta.

**Comment by Alec-Ellsworth-SK** [comment]
Can we switch a couple test units so we can test it today and then confirm?

**Comment by mpbarnwell** [comment]
> Can we switch a couple test units so we can test it today and then confirm?

Yes, thats what we're asking you to do. 

Use teleport to connect to whichever kiosk you want to test on, [unhold the current snap hold](https://snapcraft.io/docs/managing-updates#heading--hold-remove), switch to the stable channel ([something like this command](https://github.com/Sentry-Interactive/kiosk-playbook/blob/main/roles/kiosk_gdm/tasks/main.yml#L35)) and test. 

It'll switch back when the next update runs unless you set a new hold.

**Comment by Alec-Ellsworth-SK** [comment]
Perfect thank you! Will get back to you.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by mpbarnwell** [comment]
Closing this one as "won't fix" since the best we can do is a hold
